changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Added
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
    - title: Deprecated
      labels:
        - deprecated
    - title: Breaking Changes
      labels:
        - breaking
    - title: Documentation
      labels:
        - documentation
    - title: Changed
      labels:
        - "*"