name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'release/v.*.*.*'
    tags:
      - 'v*.*.*'

env:
  NuGetPackageSourceCredentials_EventStore: Username=${{ vars.ORG_GH_BOT_USERNAME }};Password=${{ secrets.ORG_GH_BOT_AUTOMATION }}

jobs:
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        framework: [ net8.0 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    name: test/${{ matrix.os }}/${{ matrix.framework }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ORG_GH_BOT_READONLY }}

      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 9.0.x
          dotnet-quality: preview

      - name: Build and Test
        run: |
          find ./tests -maxdepth 1 -type d -name "*.Tests"  -print0 \
            | xargs -I{} -0 -n1 bash -c \
            'dotnet test --configuration Release --blame --logger:"GitHubActions;report-warnings=false" --logger:"console;verbosity=normal" --results-directory=$(pwd)/test-results/$1 $1' - '{}'