name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'release/v.*.*.*'
    tags:
      - 'v*.*.*'

env:
  NuGetAudit: false
  NuGetPackageSourceCredentials_EventStore: Username=${{ vars.ORG_GH_BOT_USERNAME }};Password=${{ secrets.ORG_GH_BOT_AUTOMATION }}

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ORG_GH_BOT_READONLY }}

      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: |
            8.0.x

      - name: 'Cache NuGet'
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ github.repository_id }}

      - name: Build
        run: |
          dotnet build --configuration Release

      - name: Test
        run: |
          find ./tests -maxdepth 1 -type d -name "*.Tests"  -print0 \
            | xargs -I{} -0 -n1 bash -c \
            'dotnet test --configuration Release --no-build --blame --logger:"GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true;report-warnings=false" --logger:"console;verbosity=normal" --results-directory=$(pwd)/test-results/$1 $1' - '{}'